id: PF43CAF89
initial_creation_type: input
source_metadata:
  title: Dzong-ngön Pema Tukchok Dorje
  language: en
  description: 'Texts by and about Dzong-ngön Pema Tukchok Dorje (rdzong sngon padma
    thugs mchog rdo rje), the incarnation of Dola Jigme Kalzang:'
  volume:
    7f25197d4fed42bba9b9357bedfef993:
      title: A Simple Method of Transference for Helpless Animals
      parent: Transference
created_at: '2022-02-28T23:12:15.402519'
last_modified_at: '2022-02-28T23:12:15.402525'
